### ISSUE TITLE
Abstract "PA2EncryptedObject" interface for both personalized and non-personalized encryption

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-crypto#129]
Currently, the iOS code uses multiple class for encrypted objects:

- PA2EncryptedObject
- PA2PersonalizedEncryptedObject <= PA2EncryptedObject
- PA2NonPersonalizedEncryptedObject <= PA2EncryptedObject

We should keep this in Java as well...

**Comment by hvge** [comment]
I think this will be deprecated soon. We're moving to ECIES scheme, which is using the same object for both scenarios. Closing this ticket.
