### ISSUE TITLE
Document offline signatures

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-crypto#147]
We are missing documentation on offline signature principle.

**Comment by romanstrobl** [comment]
Are we still missing something?

See:
https://github.com/lime-company/powerauth-webflow/wiki/Off-line-Signatures-QR-Code
https://github.com/lime-company/powerauth-server/wiki/Offline-Signatures

**Comment by hvge** [comment]
The ticket is still valid. That linked documents are more about implementation details, but we're still missing info about cryptographic principles. Like what constants is used in the protocol, or overall overview of Offline Signatures. I can reuse some parts of that pa-server's document.

**Comment by romanstrobl** [comment]
I am moving the issue to the next release so that we can close release `2019.05`.
