### ISSUE TITLE
Document /pa/signature/validate endpoint

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-crypto#172]
Currently, our RESTful integration libraries publish signature verification endpoint `/pa/signature/validate` (see [sources](https://github.com/lime-company/powerauth-restful-integration/blob/develop/powerauth-restful-security-spring/src/main/java/io/getlime/security/powerauth/rest/api/spring/controller/SignatureController.java)) but the endpoint is not included in documentation of [Standard RESTful API](https://github.com/lime-company/powerauth-crypto/wiki/Standard-RESTful-API).

**Comment by romanstrobl** [comment]
I documented the endpoint:

https://github.com/wultra/powerauth-crypto/wiki/Standard-RESTful-API#validate-signature
