### ISSUE TITLE
Add alternate signature calculation to tests

### ISSUE THREAD

**Issue by hvge** [wultra/powerauth-crypto#285]
In our PowerAuth signature tests (class `PowerAuthSignatureTest`), we're validating results between two classes — `PowerAuthClientSignature` vs `PowerAuthServerSignature`. Unfortunately, both implementation uses `SignatureUtils` class under the hood. That basically means that if there's an error in the calculation, we cannot find it.

This is not critical due to fact, that we're still validating test vectors between the mobile and java imp. But I think, that we should catch such errors sooner.

**Comment by petrdvorak** [comment]
Not required anymore.
