### ISSUE TITLE
Add new /user/info endpoint

### ISSUE THREAD

**Issue by hvge** [wultra/powerauth-crypto#453]
We're going to add a new endpoint to [PowerAuth Standard RESTful API](https://developers.wultra.com/components/powerauth-crypto/develop/documentation/Standard-RESTful-API) that will provide an additional information about the user for the mobile application. The change has no impact to actual "powerauth-crypto" project implementation except the documentation.

## Getting information about user

The goal is to implement endpoint that provide additional information about the authenticated user in form of standard claims (see below).

The `userinfo` endpoint is using PowerAuth ECIES encryption witch activation scope.

#### Request

| Request parameter | Value                       |
| ----------------- | --------------------------- |
| Resource URI           | `/pa/v3/user/info` |
| Method                 | `POST`                 |
| Body                   | Standard [ECIES payload](https://developers.wultra.com/components/powerauth-crypto/develop/documentation/End-To-End-Encryption#structure-of-eciespayload) with "activation" scope |
| Body before encryption | `{}` (empty object)    |

##### Headers

| Header            | Description                 |
| ----------------- | --------------------------- |
| X-PowerAuth-Encryption | PowerAuth ECIES header |
| Content-Type      | `application/json`          |
| Accept:           | `application/json`          |

#### Response `200`

If successful, then the key-value dictionary with standard claims is encrtypted in ECIES response. For example:

```json
{
    "sub"        : "83692",
    "name"       : "Alice Adams",
    "email"      : "alice@example.com",
    "birthdate"  : "1975-12-31"
}
```
> If there are no claims defined for the user, then the empty dictionary `{}` is returned.

The JSON payload above is then encrypted in ECIES response envelope.

#### Response `4xx`, `5xx`

In case of failure, the standard PowerAuth Standard RESTful API error response is used, for example:

```json
{
  "status": "ERROR",
  "responseObject": {
    "code": "ERROR_CODE",
    "message": "ERROR_MESSAGE_IN_ENGLISH"
  }
}
```

## Supported standard claims

- [IANA Registry](https://www.iana.org/assignments/jwt/jwt.xhtml)
- [OpenID Specification](https://openid.net/specs/openid-connect-core-1_0.html#Claims)

The mobile SDK should provide the constants or the convenience getters for the following claims: `iss`, `sub`, `nbf`, `iat`, `jti`, `name`, `given_name`, `family_name`, `middle_name`, `nickname`, `preferred_username`, `profile`, `picture`, `website`, `email`, `email_verified`, `gender`, `birthdate`, `zoneinfo`, `locale`, `phone_number`, `phone_number_verified`.

**Comment by petrdvorak** [comment]
Already implemented
