### ISSUE TITLE
Make the end-to-end encryption more explicit

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-crypto#56]
Currently, a client application can deduce the transport key to protect the communication between client and server systems. It would be nice to give this feature a bit more official support, namely by:
- extending the SOAP interface by "encrypt" / "decrypt" methods
- adding support in API authentication object so that we don't have to call the SOAP interface all the time
- extending the client libraries to make this a bit more transparent on developer's side.

**Comment by petrdvorak** [comment]
I have to postpone this to 0.13.0, since we need to release 0.12.0 already...

**Comment by petrdvorak** [comment]
- [ ] extending the SOAP interface by "encrypt" / "decrypt" methods
- [ ] adding support in integration libraries so that we don't have to call the SOAP interface all the time
- [ ] extending the client libraries to make this a bit more transparent on developer's side.

**Comment by petrdvorak** [comment]
We currently seem to have everything we need for 0.13.2: a non-personalized encryption support and a base for personalized encryption. Moving to 0.14.0.

**Comment by hvge** [comment]
Not relevant anymore. It will be replaced with ECIES scheme.
