### ISSUE TITLE
Documentation broken link 

### ISSUE THREAD

**Issue by banterCZ** [wultra/powerauth-crypto#613]
Broken link at https://developers.wultra.com/components/powerauth-crypto/develop/documentation/Computing-and-Validating-Signatures 
![image](https://github.com/wultra/powerauth-crypto/assets/1705996/79357c1f-621e-4b07-84bb-ccc1d1de8ef2)
See https://github.com/wultra/enrollment-server/issues/1061

**Comment by OliverJanstaWultra** [comment]
Looks good, moving to done
