### ISSUE TITLE
Support for SSL pinning + tooling

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-crypto#87]
Currently, SSL pinning support is not included in the PowerAuth 2.0 protocol. Which is not surprising and it's a good thing, since it does not belong there. However, all mobile banks are practically dealing with this issue. I believe SSL support could be implemented as an auxiliary feature with the infrastructure we already have in place.

The idea is to extend the "/pa/activation/status" endpoint with a `certificates` element with list of currently valid certificates. The new element should be a collection of certificate fingerprints and a signatures computed using a `KEY_SERVER_MASTER_PRIVATE` key (so that client can validate authenticity using the `KEY_SERVER_MASTER_PUBLIC` key).

Response example:

``` json
{
    "status": "OK",
    "responseObject": {
        "activationId": "c564e700-7e86-4a87-b6c8-a5a0cc89683f",
        "encryptedStatusBlob": "19gyYaW5ZhdGlvblkb521fYWN0aX9JRaAhbG9duZ==",
        "certificates": [
            {
                "fingerprint": "b521fYYaW5Zhd19gyGlvblkWN0aX9JRaAhbG9duZ==",
                "signature": "X9JRaAhbG9duZ=="
            }
        ],
        "customObject": {
            "_comment": "Any object data, such as timestamp, service status info, etc."
        }
    }
}
```

After receiving the status object, client should validate fingerprint signatures and if they are valid, it should store certificates in a non-persistent storage, or a reasonably secure persistent storage (for example, KeyChain).

As a result, the `/pa/activation/status` endpoint must have relaxed SSL support which should not be an issue considering the important part of the payload is encrypted using [PowerAuth 2.0 End-to-end Encryption scheme](https://github.com/lime-company/lime-security-powerauth/wiki/Standard-RESTful-API#activation-status).

**Comment by romanstrobl** [comment]
Can we close this issue now?

**Comment by petrdvorak** [comment]
This can be closed, we implemented separate SSL pinning related repositories.

https://github.com/wultra/ssl-pinning-tool
https://github.com/wultra/ssl-pinning-ios
https://github.com/wultra/ssl-pinning-android
